### ISSUE TITLE
Ejercicio 17

### ISSUE THREAD

**Issue by cai-uba** [JuanCruz1997/CAI_-28032020-SegundosDiez-#2]
Muy bien planteado en 2 proyectos y con objetos.

Te cuento los detalles:
1) Consoles write/read nunca en libreria
2) Está buena la resolución de obtener sueldo máximo, pero no es bueno tener un método estático en una clase. Lo mejor que puede pasarnos es que una clase haga solo una función específica o si son varias, que tengan relación con el negocio. En este caso ObtenerEmpleadoSueldoMaximo no tiene mucho que ver con empleado o al menos con las características de este.
Te cuento en este caso cómo se resuelve.
2 opciones:
a) La que sabés ahora (la b no la expliqué aún), tener la clase empleado, y una clase estática por ejemplo EmpleadoHelper que tenga el método ese.
b) la mejor, tener una Clase Nómina, que tenga los atributos Area, Empresa, FechaDePago, List<Empleado> y ahi ya podes tener tu metodo no estatico ObtenerEmpleadoMasCaro por ejemplo. Eso devuelve un obj empleado y en la prop sueldo tenes su el salario mas alto y además nombre y más detalles.
Y esto ya no sería necesario en la consola.
 if (sueldo > maxSueldo)
                {
                    maxSueldo = sueldo;
                }

**Comment by JuanCruz1997** [comment]
Hola Silvio,
Modifiqué el ejercicio para que se adapte a las correcciones que me hiciste. Comentame si quedó mejor o si todavía tiene alguna cosa por mejorarle.
Gracias!

**Comment by cai-uba** [comment]
Muy bien lo de validaciones!
Lo de nómina también está bien manejado, pero hay que encararlo como una clase concreta no estática.
Fijate acá:
Nomina.ObtenerEmpleadoMasCaro(Nomina.GetEmpleados);
Estás usan 2 llamados a la misma clase, eso es un signo que se podría optimizar.
Además vos podés tener más de una nómina en una empresa, de sistemas, de ventas, etc. O incluso de otras empresas.  Igual no estás mal, porque podrís tener una clase "helper" que gestione cosas de empleados, pero en este caso una nomina es algo concreto.

La idea sería algo así (te paso ideas y a ver si lo podés encarar)
Imaginate el program:

arranca con:
Nomina n = new Nomina();

en lugar de un for, haces un while y que ingrese todos los empleados que quiera.

y por cada ingreso pedis nombre y sueldo.
ahi haces
n.AddEmpleado(new Empleado(nombre,sueldo));

y al final, cuando el usuario quiere salir del while

Empleado caro = n.ObtenerEmpleadoMasCaro();

Yo creo que a medida que puedas desarrollar estos cambios te va quedar mucho más claro 2 aspectos.
Clases concretas vs clases estáticas
Asociación entre clases (Nomina-Empleado)

**Comment by JuanCruz1997** [comment]
Hola Silvio! Hoy me pude hice un tiempito para ir corrigiendo diferentes cosas que me fuiste marcando en algunos ejercicios pasados. Acá modifiqué lo que me habías planteado respecto de la clase estática. Espero haber encarado bien tu solución propuesta.
Gracias!

**Comment by cai-uba** [comment]
Buenisimo Juan, solo sacale el static acá
        static int tamaño = 5;
        static Empleados[] e = new Empleados[tamaño];
y el new y la asignacion la podes hacer dentro del constructor. Con eso ya quedaria perfecto.

Silvio

**Comment by cai-uba** [comment]
excelente!
